# -*- coding: utf-8 -*-
"""Gas detection using thermal cameras.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_dDdiv6axWdN0KvZVRoRC5xlr-faSgT0
"""

#inside_loop

#input_from_sensor = get the sensor input here
sensor_mean = np.mean(input_from_sensor)
if(abs(sensor_mean-normal_img_mean)>abs(sensor_mean-gas_img_mean)):
  print("Gas leak")
else:
  print("No gas leak")